All the preprocessing will be done in the instruction and response column only. So in this we will refer df as these two columns only

In [ ]:
import numpy as np
import pandas as pd
from google.colab import files
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('wordnet')
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet
df = pd.read_csv('/content/Bitext_Sample_Customer_Support_Training_Dataset.csv')
df = df[['instruction', 'response']]
df

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

,instruction,response
0,question about cancelling order {{Order Number}},I've understood you have a question regarding ...
1,i have a question about cancelling oorder {{Or...,I've been informed that you have a question ab...
2,i need help cancelling puchase {{Order Number}},I can sense that you're seeking assistance wit...
3,I need to cancel purchase {{Order Number}},I understood that you need assistance with can...
4,"I cannot afford this order, cancel purchase {{...",I'm sensitive to the fact that you're facing f...
...,...,...
26867,I am waiting for a rebate of {{Refund Amount}}...,Thank you for sharing your situation regarding...
26868,how to see if there is anything wrong with my ...,Ensuring the accuracy of your restitution is o...
26869,I'm waiting for a reimbjrsement of {{Currency ...,"Firstly, I genuinely understand the importance..."
26870,I don't know what to do to see my reimbursemen...,I've understood you're unsure about how to che...
26871,I need to know if there is anything new on the...,It's completely understandable that you want t...

In [ ]:
df = df.dropna()
df

,instruction,response
0,question about cancelling order {{Order Number}},I've understood you have a question regarding ...
1,i have a question about cancelling oorder {{Or...,I've been informed that you have a question ab...
2,i need help cancelling puchase {{Order Number}},I can sense that you're seeking assistance wit...
3,I need to cancel purchase {{Order Number}},I understood that you need assistance with can...
4,"I cannot afford this order, cancel purchase {{...",I'm sensitive to the fact that you're facing f...
...,...,...
26867,I am waiting for a rebate of {{Refund Amount}}...,Thank you for sharing your situation regarding...
26868,how to see if there is anything wrong with my ...,Ensuring the accuracy of your restitution is o...
26869,I'm waiting for a reimbjrsement of {{Currency ...,"Firstly, I genuinely understand the importance..."
26870,I don't know what to do to see my reimbursemen...,I've understood you're unsure about how to che...
26871,I need to know if there is anything new on the...,It's completely understandable that you want t...

# 1. Lowering Text

In [ ]:
df = df.apply(lambda x : x.str.lower())

# 2. Remove Punctuations

In [ ]:
import re

df["instruction"] = df["instruction"].apply(
    lambda text: re.sub(r"[^\w\s]", "", text)
)
df

,instruction,response
0,question about cancelling order order number,i've understood you have a question regarding ...
1,i have a question about cancelling oorder orde...,i've been informed that you have a question ab...
2,i need help cancelling puchase order number,i can sense that you're seeking assistance wit...
3,i need to cancel purchase order number,i understood that you need assistance with can...
4,i cannot afford this order cancel purchase ord...,i'm sensitive to the fact that you're facing f...
...,...,...
26867,i am waiting for a rebate of refund amount dol...,thank you for sharing your situation regarding...
26868,how to see if there is anything wrong with my ...,ensuring the accuracy of your restitution is o...
26869,im waiting for a reimbjrsement of currency sym...,"firstly, i genuinely understand the importance..."
26870,i dont know what to do to see my reimbursement...,i've understood you're unsure about how to che...
26871,i need to know if there is anything new on the...,it's completely understandable that you want t...

# 3. Remove whitespaces

In [ ]:
df = df.apply(lambda x : x.str.strip())
df

,instruction,response
0,question about cancelling order order number,i've understood you have a question regarding ...
1,i have a question about cancelling oorder orde...,i've been informed that you have a question ab...
2,i need help cancelling puchase order number,i can sense that you're seeking assistance wit...
3,i need to cancel purchase order number,i understood that you need assistance with can...
4,i cannot afford this order cancel purchase ord...,i'm sensitive to the fact that you're facing f...
...,...,...
26867,i am waiting for a rebate of refund amount dol...,thank you for sharing your situation regarding...
26868,how to see if there is anything wrong with my ...,ensuring the accuracy of your restitution is o...
26869,im waiting for a reimbjrsement of currency sym...,"firstly, i genuinely understand the importance..."
26870,i dont know what to do to see my reimbursement...,i've understood you're unsure about how to che...
26871,i need to know if there is anything new on the...,it's completely understandable that you want t...

# 4. Tokenization

In [ ]:
from nltk.tokenize import word_tokenize
df=df.apply(lambda x:x.apply(word_tokenize))
df

,instruction,response
0,"[question, about, cancelling, order, order, nu...","[i, 've, understood, you, have, a, question, r..."
1,"[i, have, a, question, about, cancelling, oord...","[i, 've, been, informed, that, you, have, a, q..."
2,"[i, need, help, cancelling, puchase, order, nu...","[i, can, sense, that, you, 're, seeking, assis..."
3,"[i, need, to, cancel, purchase, order, number]","[i, understood, that, you, need, assistance, w..."
4,"[i, can, not, afford, this, order, cancel, pur...","[i, 'm, sensitive, to, the, fact, that, you, '..."
...,...,...
26867,"[i, am, waiting, for, a, rebate, of, refund, a...","[thank, you, for, sharing, your, situation, re..."
26868,"[how, to, see, if, there, is, anything, wrong,...","[ensuring, the, accuracy, of, your, restitutio..."
26869,"[im, waiting, for, a, reimbjrsement, of, curre...","[firstly, ,, i, genuinely, understand, the, im..."
26870,"[i, dont, know, what, to, do, to, see, my, rei...","[i, 've, understood, you, 're, unsure, about, ..."
26871,"[i, need, to, know, if, there, is, anything, n...","[it, 's, completely, understandable, that, you..."

In [ ]:
stop_words = set(stopwords.words('english'))

df = df.apply(
    lambda col: col.apply(
        lambda words: [word for word in words if word.lower() not in stop_words]
    )
)
df

,instruction,response
0,"[question, cancelling, order, order, number]","['ve, understood, question, regarding, canceli..."
1,"[question, cancelling, oorder, order, number]","['ve, informed, question, canceling, order, {,..."
2,"[need, help, cancelling, puchase, order, number]","[sense, 're, seeking, assistance, canceling, p..."
3,"[need, cancel, purchase, order, number]","[understood, need, assistance, canceling, purc..."
4,"[afford, order, cancel, purchase, order, number]","['m, sensitive, fact, 're, facing, financial, ..."
...,...,...
26867,"[waiting, rebate, refund, amount, dollars]","[thank, sharing, situation, regarding, pending..."
26868,"[see, anything, wrong, restitution]","[ensuring, accuracy, restitution, utmost, impo..."
26869,"[im, waiting, reimbjrsement, currency, symbolr...","[firstly, ,, genuinely, understand, importance..."
26870,"[dont, know, see, reimbursement, status]","['ve, understood, 're, unsure, check, status, ..."
26871,"[need, know, anything, new, restitution]","['s, completely, understandable, want, stay, u..."

# 5. Lemmatization

In [ ]:
lemmatizer = WordNetLemmatizer()

df = df.apply(
    lambda col: col.apply(
        lambda words: [
            lemmatizer.lemmatize(word, pos=wordnet.VERB)
            for word in words
        ]
    )
)
df

,instruction,response
0,"[question, cancel, order, order, number]","['ve, understand, question, regard, cancel, or..."
1,"[question, cancel, oorder, order, number]","['ve, inform, question, cancel, order, {, {, o..."
2,"[need, help, cancel, puchase, order, number]","[sense, 're, seek, assistance, cancel, purchas..."
3,"[need, cancel, purchase, order, number]","[understand, need, assistance, cancel, purchas..."
4,"[afford, order, cancel, purchase, order, number]","['m, sensitive, fact, 're, face, financial, di..."
...,...,...
26867,"[wait, rebate, refund, amount, dollars]","[thank, share, situation, regard, pending, reb..."
26868,"[see, anything, wrong, restitution]","[ensure, accuracy, restitution, utmost, import..."
26869,"[im, wait, reimbjrsement, currency, symbolrefu...","[firstly, ,, genuinely, understand, importance..."
26870,"[dont, know, see, reimbursement, status]","['ve, understand, 're, unsure, check, status, ..."
26871,"[need, know, anything, new, restitution]","['s, completely, understandable, want, stay, u..."

# 6. Spelling Correction

In [ ]:
!pip install pyspellchecker
from spellchecker import SpellChecker
spell = SpellChecker()

# Build unique word set directly from token lists
unique_words = set()
for col in ["instruction", "response"]:
    for tokens in df[col]:
        unique_words.update(tokens)

# Correct each unique word once
correction_cache = {w: (spell.correction(w) or w) for w in unique_words}

# Apply correction to each token in the list, return a corrected list (not a joined string)
def correct_tokens(tokens):
    return [correction_cache[w] for w in tokens]

df["instruction"] = df["instruction"].apply(correct_tokens)
df["response"] = df["response"].apply(correct_tokens)

Requirement already satisfied: pyspellchecker in /usr/local/lib/python3.12/dist-packages (0.9.0)

In [ ]:
df

,instruction,response
0,question about cancelling order {{Order Number}},I've understood you have a question regarding ...
1,i have a question about cancelling oorder {{Or...,I've been informed that you have a question ab...
2,i need help cancelling puchase {{Order Number}},I can sense that you're seeking assistance wit...
3,I need to cancel purchase {{Order Number}},I understood that you need assistance with can...
4,"I cannot afford this order, cancel purchase {{...",I'm sensitive to the fact that you're facing f...
...,...,...
26867,I am waiting for a rebate of {{Refund Amount}}...,Thank you for sharing your situation regarding...
26868,how to see if there is anything wrong with my ...,Ensuring the accuracy of your restitution is o...
26869,I'm waiting for a reimbjrsement of {{Currency ...,"Firstly, I genuinely understand the importance..."
26870,I don't know what to do to see my reimbursemen...,I've understood you're unsure about how to che...
26871,I need to know if there is anything new on the...,It's completely understandable that you want t...

# 7. Saving the File

In [ ]:
df.to_csv('Bitext_Sample_Customer_Support_Training_Dataset.csv', index = False)
files.download('Bitext_Sample_Customer_Support_Training_Dataset.csv')